spring:
  datasource:
    url: jdbc:h2:mem:anypost;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop   # para arrancar rápido; luego pasamos a Flyway
    show-sql: false
    open-in-view: false
  flyway:
    enabled: false            # desactivado hasta que tengamos migraciones V1

# Consola H2 (opcional para debug): http://localhost:8080/h2-console
spring.h2.console.enabled: true
spring.h2.console.path: /h2-console

logging:
  level:
    org.springframework: info